### ISSUE TITLE
Add support for multiple sets

### ISSUE THREAD

**Issue by saifahn** [saifahn/what-could-they-have#22]
## Overview

Currently, the app can only support one set. It would be useful to be able to prepare yourself for different formats. People play different formats on MTGO, in paper and on Arena.

## Tasks

- [ ] Add a set selector
- [ ] Load a new set when a set is selected
- [ ] Add loading feedback

## Notes

The current architecture has the cards stored as JSON files and the text stored as markdown files. It's unclear if these can be fetched dynamically if we're doing this all through Netlify.

- [ ] Test if we can have all the files local and be fetched dynamically

If we can't do this, then this functionality will be delayed for now. We should build an API to serve the cards and the text separately.
